// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sudan_Api.Data;

#nullable disable

namespace Sudan_Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231003052018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sudan_Api.Models.Sudan", b =>
                {
                    b.Property<int>("sudanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("SudanCategorysudanCatId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("sudanName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("sudanId");

                    b.HasIndex("SudanCategorysudanCatId");

                    b.ToTable("Sudans");
                });

            modelBuilder.Entity("Sudan_Api.Models.SudanCategory", b =>
                {
                    b.Property<int>("sudanCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sudanTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("sudanCatId");

                    b.ToTable("SudanCategories");
                });

            modelBuilder.Entity("Sudan_Api.Models.Sudan", b =>
                {
                    b.HasOne("Sudan_Api.Models.SudanCategory", null)
                        .WithMany("Sudans")
                        .HasForeignKey("SudanCategorysudanCatId");
                });

            modelBuilder.Entity("Sudan_Api.Models.SudanCategory", b =>
                {
                    b.Navigation("Sudans");
                });
#pragma warning restore 612, 618
        }
    }
}
